{"name": "Проверяем, что при передаче только логина приходит ошибка", "status": "passed", "start": 1733824513405, "stop": 1733824513505, "uuid": "bbf0cd3f-a3b9-42d4-bf34-7c8f4ef4eeab", "historyId": "bcbe32b7c87bdaa68bd357cc011e0c38", "testCaseId": "bcbe32b7c87bdaa68bd357cc011e0c38", "fullName": "tests.test_courier_login.TestLoginCourier#test_courier_login_empty_password_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-QTD43HQ"}, {"name": "thread", "value": "28308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}