{"name": "Проверяем, что без предварительного создания пользователя приходит ошибка", "status": "passed", "start": 1733829545200, "stop": 1733829545329, "uuid": "0f9d54ad-a675-4e92-b49f-5c23eb69c0ca", "historyId": "84f7280d47794422c82627c731ac2cb1", "testCaseId": "84f7280d47794422c82627c731ac2cb1", "fullName": "tests.test_courier_login.TestLoginCourier#test_unregistered_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-QTD43HQ"}, {"name": "thread", "value": "22664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}