{"name": "Проверяем, что при передаче только логина приходит ошибка", "status": "skipped", "statusDetails": {"message": "XFAIL Баг API: падает с 504 ошибкой\n\nAssertionError: assert (504 == 400)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <test_courier_login.TestCourierLogin object at 0x000001FBC5E3A4E0>, payload = {'firstName': 'ddheakejtv', 'login': 'yofemxwbxa', 'password': 'jivizkppsj'}\n\n    @allure.title(\"Проверяем, что при передаче только логина приходит ошибка\")\n    @pytest.mark.xfail(reason=\"Баг API: падает с 504 ошибкой\")\n    def test_login_without_password_returns_error(self, payload):\n        response = requests.post(CourierLoginUrls.create, data=payload)\n        assert response.status_code == 201 and response.text == '{\"ok\":true}'\n        login = payload.get(\"login\")\n        response = requests.post(CourierLoginUrls.login, data={\"login\": login})\n>       assert response.status_code == 400 and response.json()[\"message\"] == \"Недостаточно данных для входа\"\nE       assert (504 == 400)\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_courier_login.py:24: AssertionError"}, "start": 1733668885984, "stop": 1733668946187, "uuid": "a5b1d51d-960b-49f6-933a-fd4ae742751e", "historyId": "33d98d57fde56e19dbed19c2aa3afe6a", "testCaseId": "33d98d57fde56e19dbed19c2aa3afe6a", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_without_password_returns_error", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Баг API: падает с 504 ошибкой')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-5C5JKNS"}, {"name": "thread", "value": "14412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}