{"name": "Проверяем, что при передаче только логина приходит ошибка", "status": "passed", "start": 1733829545618, "stop": 1733829545733, "uuid": "d218736a-bfc8-4d4d-86da-5739c5d51a64", "historyId": "bcbe32b7c87bdaa68bd357cc011e0c38", "testCaseId": "bcbe32b7c87bdaa68bd357cc011e0c38", "fullName": "tests.test_courier_login.TestLoginCourier#test_courier_login_empty_password_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-QTD43HQ"}, {"name": "thread", "value": "22664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}