{"name": "Проверяем, что при передаче только пароля приходит ошибка", "status": "passed", "start": 1733829546277, "stop": 1733829546375, "uuid": "8069e580-f2f5-4917-88bd-7ef2f6d4c080", "historyId": "dcc847ac6551f4a17a5ba3d52ec8b071", "testCaseId": "dcc847ac6551f4a17a5ba3d52ec8b071", "fullName": "tests.test_courier_login.TestLoginCourier#test_courier_login_empty_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-QTD43HQ"}, {"name": "thread", "value": "22664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}