{"name": "Проверяем, что без предварительного создания пользователя приходит ошибка", "status": "passed", "start": 1733824512773, "stop": 1733824512861, "uuid": "bd09ea6d-7d28-453b-bf94-e0b512a56b83", "historyId": "84f7280d47794422c82627c731ac2cb1", "testCaseId": "84f7280d47794422c82627c731ac2cb1", "fullName": "tests.test_courier_login.TestLoginCourier#test_unregistered_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-QTD43HQ"}, {"name": "thread", "value": "28308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}